POST http://localhost:8080/topup
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NzNmNjk5ZS02ZjcwLTQwYTMtYTBkYS0yZDUzNmJjYjllYmMiLCJleHAiOjE3Mjk1MDQ1NTJ9.i0kAq6U9PHCpynCBKR3eFjXApVFmf8B6bZBVuLHj18A

{
    "amount": 550000.00
}